name: Go report card

on:
  schedule:
    - cron: 47 4 * * *
  push:
    branches:    
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
